services:
  - type: web
    name: tlu-news-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: singapore      # bạn có thể thay bằng 'oregon' hoặc 'frankfurt'
    branch: main
    autoDeploy: true
