name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Set up database configuration
      run: |
        sed -i "s/DB_CONNECTION=.*/DB_CONNECTION=mysql/" .env
        sed -i "s/DB_HOST=.*/DB_HOST=${{ secrets.MYSQL_HOST }}/" .env
        sed -i "s/DB_PORT=.*/DB_PORT=3306/" .env
        sed -i "s/DB_DATABASE=.*/DB_DATABASE=${{ secrets.MYSQL_DATABASE }}/" .env
        sed -i "s/DB_USERNAME=.*/DB_USERNAME=${{ secrets.MYSQL_USER }}/" .env
        sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}/" .env

    - name: Install Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Set permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for MySQL to be ready
      run: |
        sudo apt-get install -y mysql-client
        until mysql -h ${{ secrets.MYSQL_HOST }} -P 3306 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e "SHOW DATABASES;"; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.MYSQL_HOST }}
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        DB_USERNAME: ${{ secrets.MYSQL_USER }}
        DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: php artisan migrate --force

    - name: Execute tests (Unit and Feature)
      env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.MYSQL_HOST }}
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        DB_USERNAME: ${{ secrets.MYSQL_USER }}
        DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: php artisan test
